# Generated by Django 5.2.3 on 2025-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing\t'), ('Shipped', 'Shipped'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
